about/urls.py
from django.urls import path
from . import views

app_name = 'about' #for linking directly from the all_blogs page 

urlpatterns = [

    path('', views.about, name='about'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog' #for linking directly from the all_blogs page 

urlpatterns = [

    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from projects import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

about/models.py
from django.db import models
from datetime import date

class Aboutme(models.Model):
    # Creates Model class for about me here, for inputting portolio projects as objects. 
    title = models.CharField(max_length=200)
    description = models.TextField()
    url = models.URLField(blank=True)
    date = models.DateField(default = date.today)


    def __str__(self):
        return self.title

blog/models.py
from django.db import models
from datetime import date

class Myblogs(models.Model):
    # Creates Model class for the Blogs here, for inputting portolio projects as objects. 
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to = 'blog/images/', blank=True)
    url = models.URLField(blank=True)
    date = models.DateField(default = date.today)


    def __str__(self):
        return self.title

projects/models.py
from django.db import models

class Project(models.Model):
    # Creates Model class, called Project here, for inputting portolio projects as objects. 
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to = 'projects/images/')
    url = models.URLField(blank=True)
    tools = models.CharField(max_length=250, blank=True)
    blog_url = models.URLField(blank=True)

    
    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render
from .models import Aboutme


def about(request):
    # Show all blogs all limit the number with python list indexing
    entries = Aboutme.objects.order_by('-date')

    return render(request, 'about/aboutme.html',{'entries':entries})

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Myblogs


def all_blogs(request):
    # Show all blogs all limit the number with python list indexing
    blogposts = Myblogs.objects.order_by('-date')[:3]

    return render(request, 'blog/all_blogs.html',{'myblogs':blogposts})

def detail(request, blog_id):
    blog = get_object_or_404(Myblogs, pk=blog_id)
    return render(request, 'blog/details.html',{'blog':blog})

projects/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    #Create Homepage and pass portfolio projects to it
    myprojects = Project.objects.all()

    return render(request,'projects/home.html', {'myprojects':myprojects})

about/templates/about/aboutme.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">About me</h1>
    
    <div class="row justify-content-md-center">
        <div class="col-4 py-3 px-lg-5 bg-light">
            <div>
                <img src = "{% static 'projects/samurailogo.png' %}" width="300" height="300" class="img-fluid">
            </div>
            <div class="container-fluid" id="profile_data">
                <div id="profile" class="container-fluid">
                    <h3>Profile</h3>
                    <p>
                        <span class="icons_svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16">
                        <path fill-rule="evenodd" d="M12 2.5a5.5 5.5 0 00-3.096 10.047 9.005 9.005 0 00-5.9 8.18.75.75 0 001.5.045 7.5 
                        7.5 0 0114.993 0 .75.75 0 101.499-.044 9.005 9.005 0 00-5.9-8.181A5.5 5.5 0 0012 2.5zM8 8a4 4 0 118 0 4 4 0 01-8 0z">
                        </path>
                    </svg></span> 
                    Idowu Odesanmi
                    <span class="verified"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16">
                        <path d="M17.03 9.78a.75.75 0 00-1.06-1.06l-5.47 5.47-2.47-2.47a.75.75 0 00-1.06 1.06l3 3a.75.75 0 001.06 0l6-6z">
                        </path>
                        <path fill-rule="evenodd" d="M14.136 1.2a3.61 3.61 0 00-4.272 0L8.489 2.21a2.11 2.11 0 01-.929.384l-1.686.259a3.61
                        3.61 0 00-3.021 3.02L2.594 7.56a2.11 2.11 0 01-.384.929L1.2 9.864a3.61 3.61 0 000 4.272l1.01 1.375c.2.274.333.593.384.929l.259 
                        1.686a3.61 3.61 0 003.02 3.021l1.687.259c.336.051.655.183.929.384l1.375 1.01a3.61 3.61 0 004.272 0l1.375-1.01a2.11 2.11 0 
                        01.929-.384l1.686-.259a3.61 3.61 0 003.021-3.02l.259-1.687a2.11 2.11 0 01.384-.929l1.01-1.375a3.61 3.61 0 000-4.272l-1.01-1.375a2.11 
                        2.11 0 01-.384-.929l-.259-1.686a3.61 3.61 0 00-3.02-3.021l-1.687-.259a2.11 2.11 0 01-.929-.384L14.136 1.2zm-3.384 1.209a2.11 2.11 0 
                        012.496 0l1.376 1.01a3.61 3.61 0 001.589.658l1.686.258a2.11 2.11 0 011.765 1.766l.26 1.686a3.61 3.61 0 00.657 1.59l1.01 1.375a2.11 2.11 0 
                        010 2.496l-1.01 1.376a3.61 3.61 0 00-.658 1.589l-.258 1.686a2.11 2.11 0 01-1.766 1.765l-1.686.26a3.61 3.61 0 00-1.59.657l-1.375 1.01a2.11 2.11 
                        0 01-2.496 0l-1.376-1.01a3.61 3.61 0 00-1.589-.658l-1.686-.258a2.11 2.11 0 01-1.766-1.766l-.258-1.686a3.61 3.61 0 00-.658-1.59l-1.01-1.375a2.11 
                        2.11 0 010-2.496l1.01-1.376a3.61 3.61 0 00.658-1.589l.258-1.686a2.11 2.11 0 011.766-1.766l1.686-.258a3.61 3.61 0 001.59-.658l1.375-1.01z">
                        </path>
                    </svg></span>
                    </p>
                    <p>
                        <span class="icons_svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
                            <path fill-rule="evenodd" d="M11.536 3.464a5 5 0 010 7.072L8 14.07l-3.536-3.535a5 5 0 117.072-7.072v.001zm1.06 8.132a6.5 6.5 0 10-9.192 
                            0l3.535 3.536a1.5 1.5 0 002.122 0l3.535-3.536zM8 9a2 2 0 100-4 2 2 0 000 4z">
                            </path>
                        </svg> </span>
                        Lagos, Nigeria
                    </p>
                    <p>Phone: +2348168185799</p>
                    <p style="word-wrap: break-word;">
                        <span class="icons_svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16">
                            <path fill-rule="evenodd" d="M1.75 3A1.75 1.75 0 000 4.75v14c0 .966.784 1.75 1.75 1.75h20.5A1.75 1.75 0 0024 18.75v-14A1.75 1.75 0 0022.25 
                            3H1.75zM1.5 4.75a.25.25 0 01.25-.25h20.5a.25.25 0 01.25.25v.852l-10.36 7a.25.25 0 01-.28 0l-10.36-7V4.75zm0 2.662V18.75c0 .138.112.25.25.25h20.5a.25.25 
                            0 00.25-.25V7.412l-9.52 6.433c-.592.4-1.368.4-1.96 0L1.5 7.412z">
                            </path>
                        </svg></span>
                        odesanmiidowu@gmail.com
                    </p>
                    <div class="work_education">
                        <h3>Work Status</h3>
                            <p>Data Scientist, Web Developer</p>
                        <h3>Education</h3>
                            <p>
                                <span class="icons_svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16">
                                    <path fill-rule="evenodd" d="M12.292 2.06a.75.75 0 00-.584 0L.458 6.81a.75.75 0 000 1.38L4.25 9.793v3.803a2.901 2.901 0 00-1.327.757c-.579.58-.923 
                                    1.41-.923 2.43v4.5c0 .248.128.486.335.624.06.04.117.073.22.124.124.062.297.138.52.213.448.149 1.09.288 1.925.288s1.477-.14 1.925-.288c.223-.075.396-.15.52-.213a2.11 
                                    2.11 0 00.21-.117A.762.762 0 008 21.28v-4.5c0-1.018-.344-1.85-.923-2.428a2.9 2.9 0 00-1.327-.758v-3.17l5.958 2.516a.75.75 0 00.584 0l5.208-2.2v4.003a2.552 2.552 0 
                                    01-.079.085 4.057 4.057 0 01-.849.65c-.826.488-2.255 1.021-4.572 1.021-.612 0-1.162-.037-1.654-.1a.75.75 0 00-.192 1.487c.56.072 1.173.113 1.846.113 2.558 0 4.254-.592 
                                    5.334-1.23.538-.316.914-.64 1.163-.896a2.84 2.84 0 00.392-.482h.001A.75.75 0 0019 15v-4.892l4.542-1.917a.75.75 0 000-1.382l-11.25-4.75zM5 15c-.377 
                                    0-.745.141-1.017.413-.265.265-.483.7-.483 1.368v4.022c.299.105.797.228 1.5.228s1.201-.123 1.5-.228V16.78c0-.669-.218-1.103-.483-1.368A1.431 1.431 0 005 15zm7-3.564L2.678 
                                    7.5 12 3.564 21.322 7.5 12 11.436z">
                                    </path>
                                </svg></span>
                                BSc. Chemical Engineering 
                            </p>
    
                    </div>
                </div>
                
                
            </div>



        </div>


        <div class="col-8 justify-content-md-center my-3">
            <div class="container">
                <h2>Summary</h2>
                <p>I'm an engineer turned data professional who loves building and deploying apps, data pipelines and machine learning models.
                     My latest model, deployed as a web app, helps emergency responders and aid organisations detect victims caught in disasters using social media posts for a particular location. 
                     Right now, I am working on building a movie recommendation web app for my friends and interested people in public.
                    <em>Skills: Python, JavaScript, SQL, Django, BootStrap, and Excel</em></p>
                <!--
                <h2>Sed Vulputate Ut Mus Ipsum Pede</h2>
                <p>Accumsan pharetra magna. Non urna cras suspendisse hac fermentum fermentum phasellus sed nibh dapibus dis et. Maecenas non blandit potenti risus nullam natoque, ornare nunc 
                    maecenas facilisis nam pulvinar accumsan, ut placerat nullam pellentesque mattis varius, aliquet vel hendrerit aliquam.</p>
            </div>
-->

            <div class="container-fluid" style="margin-top: 20px;">
                <div class="">
                    <h2>Skills</h2>
                </div>
                <hr>
                {% for skill in entries %}
                <div>
                    <div> <h5 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"> {{ skill.title }}</h5></div>
                    <div><p style="font-style: oblique;">{{ skill.description|safe }}</p></div>
                <hr> 
                
                </div>
                {% endfor %}
            </div>
           

        </div>
                
    </div>
 
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Journey in Tech!</h2>
                        <div id="content">
                            <ul class="timeline">
                                <li class="event" data-date="In progress">
                                    <h3>Full Stack Web Dev</h3>
                                    <p>Building full stack web applications</p>
                                </li>
                                <li class="event" data-date="01.2022">
                                    <h3>Django 3 - Full Stack Websites</h3>
                                    <p>Completed 2 web development projects including this website.</p>
                                </li>
                                <li class="event" data-date="12.2021">
                                    <h3>Udacity Datascience Nanodegree</h3>
                                    <p>Completed a 5-Month Data science Nanodegree with Udacity.</p>
                                </li>
                                <li class="event" data-date="11.2021">
                                    <h3>AWS ML Foundations</h3>
                                    <p>Completed the Udacity AWS Machine Learning Foundation course </p>
                                </li>
                                <li class="event" data-date="09.2021">
                                    <h3>Microsoft Excel Expert</h3>
                                    <p>Certified a Microsoft 365 Apps and Office Expert</p>
                                </li>
                                <li class="event" data-date="04.2021">
                                    <h3>Python for Data Science and AI</h3>
                                    <p>Completed the Coursera IBM AI course.</p>
                                </li>
                                <li class="event" data-date="03.2021">
                                    <h3>SQL Bootcamp</h3>
                                    <p>Completed the Udemy "Complete SQL Bootcamp" </p>
                                </li>
                                <li class="event" data-date="09.2020">
                                    <h3>Python for Data Science and Machine Learning</h3>
                                    <p>Completed a 3-month comprehensive datascience course with Python.</p>
                                </li>
                                <li class="event" data-date="08.2020">
                                    <h3>Programming Foundations:Databases</h3>
                                    <p>Completed a LinkedIn Learning course on relational databases and data modelling.</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

blog/templates/blog/all_blogs.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>


{% for blog in myblogs %}
<div class = "row justify-content-center my-3">
  <div class = "col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }} </h2> 
    </a>
    <img src="{{ blog.image.url }}" class="img-fluid mb-2"> 
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper}}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  {% if blog.url %}
  <a href= "{{ blog.url }}" class="btn">
    <img src="{% static 'projects/medium.png' %}" width="20" height="20" class="d-inline-block align-top" alt="Medium">
</a>
    {% endif %}  
  </div>
</div>
{% endfor %}


{% endblock %}

blog/templates/blog/details.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle"> {{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">--{{ blog.date|date:'F jS Y' }}--</h5>
{% if blog.url %}
    <a href= "{{ blog.url }}" class="btn">
        <img src="{% static 'projects/medium.png' %}" width="20" height="20" class="d-inline-block align-top" alt="Medium">
    </a>
    {% endif %}<br>
<div class="container text-center">
    <img src="{{ blog.image.url }}" class="img-fluid mb-2"> 
</div>
<div class="container">
    {{ blog.description|safe }}
</div>
<br>
<div class="container">
    <p>Continue on <a href="{{ blog.url }}" class="btn btn-info">Medium</a> </p>
</div>
<hr>
{% endblock %}

projects/templates/projects/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <title>Idowu Odesanmi</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
 
   
    <link rel="stylesheet" href="{% static 'projects/custom.css' %}">
    <link rel="icon" type="image/png" href="{% static 'projects/samurailogo.png' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
  
 


  </head>
  <body>

    <nav id="topNav" class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'projects/samurailogo.png' %}" width="40" height="40" class="d-inline-block align-top" alt="">
          Idowu Odesanmi
        </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
      data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.github.com/joshasgard" target="_blank">Github</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% static 'projects/Idowu_Odesanmi_Resume.pdf' %}" target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/idowu-odesanmi" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>


        </ul>
        <!-- Search Box....
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </div>
    </nav>
    <div class="container">
 
    {% block content %} {% endblock %}
    </div>
    <br>
    <p><i>
    Copyright &copy; 2021. Idowu Odesanmi. Web Developer and Data Scientist </i></p>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    -->
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>

projects/templates/projects/home.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}
    <div class = "row justify-content-center my-3"> 
      <div class="col-5">
        <img src = "{% static 'projects/smilinginger.jpg' %}" class="img-fluid">
    </div>

    <div class="row justify-content-center mb-3">
      <div class="col-md-9 text-center">
        <h3 id="hometext"><b>Welcome! People of Earth.</b>👽 <br> <b>I'm Idowu. I'm a developer, a data scientist and an engineer. </b> 😊</h3>
      </div>
    </div>

    <p class="h2"><b>Project Portfolio</b></p>
    <hr>
    <p class="text-justify"> From web development with Django to data visualizations projects, Python development, Natural Language Processing,
                            Recommendation Engines, Machine Learning and so many more!
                          Scroll through my expanding portfolio of projects below and enjoy!.😊 </p>
    <div class = "row">
      {% for project in myprojects %}
      <div class="col-lg-4 col-md-6">

        {% if project.url %}
        <a href= "{{ project.url }}" class="btn btn-info"> 
          <img src="{{ project.image.url }}" class="img-fluid mb-2">
        </a>
        {% else %}
        <img src="{{ project.image.url }}" class="img-fluid mb-2">

        {% endif %}

      <h3>{{ project.title }} </h3>
      <p>{{ project.description }}</p>
      <p style="font-family: cursive;">{{ project.tools }}</p>

      <a href= "{{ project.url }}" class="btn">
        <img src="{% static 'projects/githublogo.png' %}" width="20" height="20" class="d-inline-block align-top" alt="Github">
      </a>
      |
      <a href= "{{ project.blog_url }}" class="btn">
        <img src="{% static 'projects/medium.png' %}" width="20" height="20" class="d-inline-block align-top" alt="Medium">
      </a>
      

      </div>
      {% endfor %}
    </div>

{% endblock %}